project:
  type: website

website:
  title: "Karol Bolbotowski"
  description: "Academic website"
  site-url: "https://kbolbotowski.github.io"
  navbar:
    pinned: true
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Talks
        href: talks.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
  page-footer:
    left: "© 2026 Karol Bolbotowski"
    right:
      - text: Email
        href: "mailto:karol.bolbotowski@pw.edu.pl"
      - text: GitHub
        href: "https://github.com/kbolbotowski"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

bibliography: publications.bib
